version: '3'
services:
  nginx:
    build: ../../../RampUp_frontend/nginx
    image: nginx
    ports:
      - "8009:8009"
    networks:
      - mynetwork
    depends_on:
      - web

  web:
    build: ../../../RampUp_frontend/frontend
    image: web
    environment:
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
      PORT: 8080
      AUTH_API_ADDRESS: http://auth:8081
      TODOS_API_ADDRESS: http://todos:8082
    ports:
      - 8080:8080
    networks:
      - mynetwork
    depends_on:
      - zipkin
      - auth
      - todos
      - users

  auth:
    build: ../../../RampUp_login/auth-api
    image: auth
    environment:
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
      AUTH_API_PORT: 8081
      JWT_SECRET: PRFT
      USERS_API_ADDRESS: http://users:8083
    ports:
      - 8000:8000
    networks:
      - mynetwork
    depends_on:
      - zipkin
      - users

  users:
    build: ../../../RampUp_login/users-api
    image: users
    environment:
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      SERVER_PORT: 8083
      JWT_SECRET: PRFT
    ports:
      - 8083:8083
    networks:
      - mynetwork
    depends_on:
      - zipkin

  todos:
    build: ../../../RampUp_TODO/todos-api
    image: todos
    environment:
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
      TODO_API_PORT: 8082
      JWT_SECRET: PRFT
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
    ports:
      - 8082:8082
    networks:
      - mynetwork
    depends_on:
      - zipkin
      - users

  redis:
    build: ../../../RampUp_TODO/redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - mynetwork

  log:
    build: ../../../RampUp_TODO/log-message-processor
    image: log
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    networks:
      - mynetwork
    depends_on:
      - zipkin
      - redis

  zipkin:
    build: ../../../RampUp_TODO/zipkin
    image: zipkin
    ports:
      - 9411:9411
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge